# ==============================
# Android Configuration
# ==============================

platformName=Android
automationName=UiAutomator2

deviceName=Xiaomi
platformVersion=15
udid=2eb84182
appPackage=com.swaglabsmobileapp
appActivity=com.swaglabsmobileapp.MainActivity
appWaitActivity=com.swaglabsmobileapp.SplashActivity,com.swaglabsmobileapp.MainActivity

# Application
app=src/test/resources/apps/AndroidApp.apk
