# ==============================
# iOS Configuration
# ==============================

platformName=iOS
automationName=XCUITest

deviceName=iPhone 16
platformVersion=18
udid=

# Application
app=/path/to/your/application.app